#!/usr/bin/env node
'use strict';

/**
 * Derive the museum's exhibit counts from the exhibits themselves.
 *
 * These numbers are quoted on roughly a dozen surfaces — the homepage, the
 * museum map, every exhibit's "N of 140" chip, the README, the search status
 * line, the footer, the sitemap comment. They have drifted four separate times,
 * because each surface carried its own hardcoded copy and nothing checked them
 * against each other, or against reality.
 *
 * This script computes them from ground truth (what is actually on disk) and
 * writes data/exhibit-counts.json. tests/test-counts.js then asserts that every
 * surface agrees with it, so a fifth drift fails the build instead of shipping.
 *
 * Usage: node scripts/build-counts.js [--check]
 *   --check  print the counts and exit without writing
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// §158-160. These live in ciphers/ for URL reasons but are protocol exhibits,
// not cipher exhibits, and the site counts them separately.
const PROTOCOL_EXHIBITS = ['ecdsa', 'shamir-secret-sharing', 'zero-knowledge-proofs'];

function htmlFiles(dir) {
  return fs.readdirSync(path.join(ROOT, dir))
    .filter(f => f.endsWith('.html'))
    .map(f => f.slice(0, -5));
}

function computeCounts() {
  const cipherPages = htmlFiles('ciphers');
  const ciphers = cipherPages.filter(s => !PROTOCOL_EXHIBITS.includes(s)).length;

  // index.html is the wing's landing page, not an exhibit.
  const foundations = htmlFiles('hall-of-foundations').filter(s => s !== 'index').length;

  const protocols = PROTOCOL_EXHIBITS.length;
  const halls = htmlFiles('halls').length;

  return {
    ciphers,
    foundations,
    protocols,
    halls,
    total: ciphers + foundations + protocols,
    // §-ranges the prose quotes: Foundations runs from the first number after
    // the cipher exhibits, and the protocol exhibits follow it.
    foundationsFirst: ciphers + 1,
    foundationsLast: ciphers + foundations,
    protocolsFirst: ciphers + foundations + 1,
    protocolsLast: ciphers + foundations + protocols
  };
}

// Importing this module must not write anything — tests/test-counts.js requires
// it purely to recompute ground truth.
if (require.main === module) {
  const counts = computeCounts();

  if (process.argv.includes('--check')) {
    console.log(JSON.stringify(counts, null, 2));
    process.exit(0);
  }

  const out = path.join(ROOT, 'data', 'exhibit-counts.json');
  fs.writeFileSync(out, JSON.stringify({
    _comment: 'GENERATED by scripts/build-counts.js — do not hand-edit. ' +
              'Guarded by tests/test-counts.js.',
    ...counts
  }, null, 2) + '\n');

  console.log('Exhibit counts →', path.relative(ROOT, out));
  console.log(`  ${counts.ciphers} cipher exhibits`);
  console.log(`  ${counts.foundations} Hall of Foundations (§${counts.foundationsFirst}–${counts.foundationsLast})`);
  console.log(`  ${counts.protocols} modern-protocol (§${counts.protocolsFirst}–${counts.protocolsLast})`);
  console.log(`  ${counts.total} total across ${counts.halls} halls`);
}

module.exports = { computeCounts, PROTOCOL_EXHIBITS };
