/* ec-math.test.js — run: node ec-math.test.js
   Exits non-zero on failure for CI. Covers the F_p curve arithmetic behind
   Exhibit 142 and the real-number group law behind Exhibit 150. */
"use strict";
var EC = require("./ec-math.js");

var passed = 0, failed = 0;
function assert(cond, msg) { if (cond) passed++; else { failed++; console.error("  ✗ FAIL: " + msg); } }

// ---- the textbook curve y^2 = x^3 + 2x + 2 over F_17 ----
var A = 2, B = 2, P17 = 17;
var pts = EC.ecPoints(A, B, P17);
// This curve famously has 19 points including infinity -> 18 affine points.
assert(pts.length === 18, "y^2 = x^3+2x+2 over F_17 has 18 affine points (19 with infinity)");
// every enumerated point satisfies the curve equation
assert(pts.every(function (P) { return EC.ecIsOnCurve(P, A, B, P17); }),
  "every enumerated point is on the curve");

// group law basics with G = (5,1), a known generator of the full 19-point group
var G = [5, 1];
assert(EC.ecIsOnCurve(G, A, B, P17), "(5,1) is on the curve");
// identity: P + infinity = P
assert(EC.ecAdd(G, null, A, P17) === G, "P + infinity = P");
assert(EC.ecAdd(null, G, A, P17) === G, "infinity + P = P");
// inverse: P + (-P) = infinity
assert(EC.ecAdd(G, [G[0], EC.mod(-G[1], P17)], A, P17) === null, "P + (-P) = infinity");
// doubling lands on the curve
var G2 = EC.ecAdd(G, G, A, P17);
assert(EC.ecIsOnCurve(G2, A, B, P17), "2G is on the curve");
assert(G2[0] === 6 && G2[1] === 3, "2G = (6,3), the textbook value");
// closure + commutativity across all pairs of points
var closed = true, commutes = true;
for (var i = 0; i < pts.length; i++) {
  for (var j = 0; j < pts.length; j++) {
    var S = EC.ecAdd(pts[i], pts[j], A, P17);
    if (!EC.ecIsOnCurve(S, A, B, P17)) closed = false;
    var T = EC.ecAdd(pts[j], pts[i], A, P17);
    var same = (S === null && T === null) ||
      (S !== null && T !== null && S[0] === T[0] && S[1] === T[1]);
    if (!same) commutes = false;
  }
}
assert(closed, "addition is closed over all point pairs");
assert(commutes, "addition commutes over all point pairs");
// the group generated by G has order 19 (prime -> the whole group is cyclic)
var walk = G, order = 1;
while (walk !== null) { walk = EC.ecAdd(walk, G, A, P17); order++; }
assert(order === 19, "G = (5,1) generates a group of order 19");

// ---- Hasse bound sanity for the primes Exhibit 142 offers ----
[11, 17, 23, 41, 67, 97].forEach(function (p) {
  var n = EC.ecPoints(A, B, p).length + 1; // + infinity
  assert(Math.abs(n - (p + 1)) <= 2 * Math.sqrt(p),
    "Hasse bound holds for p = " + p + " (N = " + n + ")");
});

// ---- the real group law (Exhibit 150: y^2 = x^3 + x + 1) ----
var a = 1, b = 1;
assert(EC.ecIsSmooth(a, b), "y^2 = x^3+x+1 is smooth (nonzero discriminant)");
assert(!EC.ecIsSmooth(0, 0), "y^2 = x^3 is a cusp — not smooth");
assert(!EC.ecIsSmooth(-3, 2), "4(-3)^3 + 27(2)^2 = 0 — node, not smooth");
function onReal(P) { return Math.abs(P[1] * P[1] - EC.curveY2(P[0], a, b)) < 1e-6; }
var Pr = [0, 1];                       // 1^2 = 0 + 0 + 1  ✓
var Qr = [2, Math.sqrt(11)];           // y^2 = 8 + 2 + 1 = 11
assert(onReal(Pr) && onReal(Qr), "test points are on the real curve");
var res = EC.ecAddReal(Pr, Qr, a);
assert(onReal(res.sum), "P+Q lands on the curve");
assert(onReal(res.third), "third intersection lies on the curve");
assert(Math.abs(res.third[1] + res.sum[1]) < 1e-9, "sum is the reflection of the third intersection");
// tangent case: P + P
var dbl = EC.ecAddReal(Pr, Pr, a);
assert(onReal(dbl.sum), "2P (tangent case) lands on the curve");
// the chord through P, Q, and the third point is a straight line
var slope = (Qr[1] - Pr[1]) / (Qr[0] - Pr[0]);
var lineY = Pr[1] + slope * (res.third[0] - Pr[0]);
assert(Math.abs(lineY - res.third[1]) < 1e-6, "third intersection is collinear with P and Q");

console.log("\nec-math: " + passed + " passed, " + failed + " failed");
process.exit(failed ? 1 : 0);
